---
abstract: 'Catch application errors and emit them somewhere'
author:
  - 'Chisel Wright C<< <chisel@herlpacker.co.uk> >>'
build_requires:
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Runtime: 5.71001
  Catalyst::Test: 0
  Config::General: 0
  DateTime: 0.42
  ExtUtils::MakeMaker: 6.42
  File::Find::Rule: 0.30
  File::Path: 0
  File::Slurp: 9999.12
  FindBin: 0
  MIME::Lite: 3.023
  Path::Class: 0.16
  Sys::Hostname: 0
  Test::More: 0.72
  Test::Simple: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ErrorCatcher
no_index:
  directory:
    - inc
    - t
recommends:
  DateTime: 0.42
  File::Slurp: 9999.12
  MIME::Lite: 3.023
  Path::Class: 0.16
requires:
  Catalyst::Runtime: 5.71001
  Class::Data::Accessor: 0
  IO::File: 0
  MRO::Compat: 0
  perl: 5.8.1
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.6.3
