---
abstract: 'Catch application errors and emit them somewhere'
author:
  - 'Chisel Wright C<< <chisel@herlpacker.co.uk> >>'
build_requires:
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0.72
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ErrorCatcher
no_index:
  directory:
    - inc
    - t
recommends:
  MIME::Lite: 3.023
requires:
  Catalyst::Runtime: 0
  Class::Data::Accessor: 0
  IO::File: 0
  MRO::Compat: 0
  UNIVERSAL::can: 0
  perl: 5.8.1
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.2.1
