---
abstract: 'Catch application errors and emit them somewhere'
author:
  - 'Chisel Wright <chisel@chizography.net>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Test: 0
  Config::General: 0
  DateTime: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Slurp: 0
  FindBin::libs: 0
  IO::File: 0
  MIME::Lite: 0
  MRO::Compat: 0
  Moose: 0
  Path::Class: 0
  Sys::Hostname: 0
  Test::Exception: 0
  Test::More: 0.92
  overload: 0
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ErrorCatcher
requires:
  Class::Data::Accessor: 0
  DateTime: 0
  File::Slurp: 0
  IO::File: 0
  MIME::Lite: 0
  MRO::Compat: 0
  Path::Class: 0
  Sys::Hostname: 0
  perl: 5.008001
version: 0.0.8.5
