---
abstract: 'Catch application errors and emit them somewhere'
author:
  - 'Chisel Wright <chisel@chizography.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-ErrorCatcher
requires:
  Catalyst: 5.80
  Catalyst::Controller::MessageDriven: 0
  Catalyst::Engine::Stomp: 0.07
  Catalyst::Plugin::StackTrace: 0.10
  Catalyst::Runtime: 5.80
  Data::Rx: 0.007
  Data::Serializer: 0.49
  Data::Serializer::JSON: 0.03
  Data::Visitor: 0.26
  DateTime: 0.4304
  DateTime::Format::ISO8601: 0.07
  File::Pid: 1.01
  FindBin::libs: 1.42
  JSON::Any: 1.22
  Log::Log4perl: 1.17
  Module::Pluggable: 3.9
  Moose: 0.93
  MooseX::Types: 0.20
  Net::Stomp: 0.38
  Path::Class: 0.17
  Scalar::Util: 1.19
  Test::Exception: 0.27
  Test::More: 0.92
  Test::UseAllModules: 0.12
  Time::HiRes: 1.86
  version: 0.76
version: 0.0.8.1
